
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace bmc
{ 
    public enum ItemType
    {
        NONE = 0,
        GOLD = 1,
    }

} 

