
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace bmc
{
public sealed partial class localization : Luban.BeanBase
{
    public localization(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Tc = _buf.ReadString();
        En = _buf.ReadString();
        Jp = _buf.ReadString();
        Sc = _buf.ReadString();
    }

    public static localization Deserializelocalization(ByteBuf _buf)
    {
        return new localization(_buf);
    }

    public readonly string Id;
    public readonly string Tc;
    public readonly string En;
    public readonly string Jp;
    public readonly string Sc;
   
    public const int __ID__ = -812005735;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "tc:" + Tc + ","
        + "en:" + En + ","
        + "jp:" + Jp + ","
        + "sc:" + Sc + ","
        + "}";
    }
}
}

