
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace bmc
{
/// <summary>
/// 禮包
/// </summary>
public sealed partial class Package : Luban.BeanBase
{
    public Package(ByteBuf _buf) 
    {
        {int n0 = _buf.ReadSize(); Icon = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Icon.Add(_e0);}}
        Content = _buf.ReadInt();
        Quantity = _buf.ReadInt();
        Rate = _buf.ReadInt();
    }

    public static Package DeserializePackage(ByteBuf _buf)
    {
        return new Package(_buf);
    }

    public readonly System.Collections.Generic.List<int> Icon;
    public readonly int Content;
    public readonly int Quantity;
    public readonly int Rate;
   
    public const int __ID__ = 857590822;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "icon:" + Luban.StringUtil.CollectionToString(Icon) + ","
        + "content:" + Content + ","
        + "quantity:" + Quantity + ","
        + "rate:" + Rate + ","
        + "}";
    }
}
}

