
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace bmc
{
public partial class Tables
{
    public Tblocalization Tblocalization {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        Tblocalization = new Tblocalization(loader("tblocalization"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        Tblocalization.ResolveRef(this);
    }
}

}
