
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace bmc
{
public partial class Tblocalization
{
    private readonly System.Collections.Generic.Dictionary<string, localization> _dataMap;
    private readonly System.Collections.Generic.List<localization> _dataList;
    
    public Tblocalization(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, localization>(n);
        _dataList = new System.Collections.Generic.List<localization>(n);
        for(int i = n ; i > 0 ; --i)
        {
            localization _v;
            _v = global::bmc.localization.Deserializelocalization(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, localization> DataMap => _dataMap;
    public System.Collections.Generic.List<localization> DataList => _dataList;

    public localization GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public localization Get(string key) => _dataMap[key];
    public localization this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

